title = "123"

[servers]

  [servers.beta]
    dc = "eqdc10"
    ip = "10.0.0.2"

  [servers.alpha]
    dc = "eqdc10"
    ip = "10.0.0.1"

[clients]
  hosts = ["alpha","omega"]
  data = [["gamma","delta"],[1,2]]

[owner]
  dob = 1979-05-27T07:32:00-08:00
  name = "Tom Preston-Werner"

[database]
  server = "192.168.1.1"
  enabled = true
  ports = [8001,8001,8002]
  connection_max = 5000
